import { GitHubRepository } from "./types";

export const MOCK_REPOSITORIES: GitHubRepository[] = [
  {
    id: "10270250",
    name: "react",
    fullName: "facebook/react",
    owner: {
      login: "facebook",
      avatarUrl: "https://avatars.githubusercontent.com/u/69631?v=4",
      htmlUrl: "https://github.com/facebook",
    },
    description: "The library for web and native user interfaces.",
    htmlUrl: "https://github.com/facebook/react",
    stargazersCount: 231450,
    forksCount: 46820,
    openIssuesCount: 1420,
    subscribersCount: 6600,
    language: "JavaScript",
    topics: ["react", "frontend", "javascript", "ui", "declarative", "jsx"],
    updatedAt: "2025-02-24T18:30:00Z",
    createdAt: "2013-05-24T16:15:54Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "main",
    weeklyGrowthStars: 1850,
  },
  {
    id: "713023402",
    name: "ollama",
    fullName: "ollama/ollama",
    owner: {
      login: "ollama",
      avatarUrl: "https://avatars.githubusercontent.com/u/149818302?v=4",
      htmlUrl: "https://github.com/ollama",
    },
    description: "Get up and running with Llama 3.3, Mistral, Gemma 2, DeepSeek-R1, and other large language models.",
    htmlUrl: "https://github.com/ollama/ollama",
    stargazersCount: 124800,
    forksCount: 9450,
    openIssuesCount: 680,
    subscribersCount: 1890,
    language: "Go",
    topics: ["ai", "llm", "llama", "deepseek", "local-ai", "go", "machine-learning"],
    updatedAt: "2025-02-25T11:10:00Z",
    createdAt: "2023-07-12T20:11:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "main",
    weeklyGrowthStars: 4200,
  },
  {
    id: "70298455",
    name: "next.js",
    fullName: "vercel/next.js",
    owner: {
      login: "vercel",
      avatarUrl: "https://avatars.githubusercontent.com/u/14985020?v=4",
      htmlUrl: "https://github.com/vercel",
    },
    description: "The React Framework for the Web. Created by Vercel.",
    htmlUrl: "https://github.com/vercel/next.js",
    stargazersCount: 128500,
    forksCount: 26900,
    openIssuesCount: 2310,
    subscribersCount: 2450,
    language: "TypeScript",
    topics: ["nextjs", "react", "framework", "ssr", "typescript", "fullstack"],
    updatedAt: "2025-02-25T14:45:00Z",
    createdAt: "2016-10-05T23:32:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "canary",
    weeklyGrowthStars: 1420,
  },
  {
    id: "16656000",
    name: "linux",
    fullName: "torvalds/linux",
    owner: {
      login: "torvalds",
      avatarUrl: "https://avatars.githubusercontent.com/u/1024025?v=4",
      htmlUrl: "https://github.com/torvalds",
    },
    description: "Linux kernel source tree maintained by Linus Torvalds.",
    htmlUrl: "https://github.com/torvalds/linux",
    stargazersCount: 186400,
    forksCount: 55200,
    openIssuesCount: 0,
    subscribersCount: 8900,
    language: "C",
    topics: ["linux", "kernel", "operating-system", "c", "systems-programming"],
    updatedAt: "2025-02-25T08:00:00Z",
    createdAt: "2011-09-04T22:42:00Z",
    license: { key: "gpl-2.0", name: "GNU General Public License v2.0", spdxId: "GPL-2.0" },
    defaultBranch: "master",
    weeklyGrowthStars: 980,
  },
  {
    id: "450982541",
    name: "bun",
    fullName: "oven-sh/bun",
    owner: {
      login: "oven-sh",
      avatarUrl: "https://avatars.githubusercontent.com/u/108928775?v=4",
      htmlUrl: "https://github.com/oven-sh",
    },
    description: "Incredibly fast JavaScript & TypeScript all-in-one toolkit: runtime, bundler, test runner, package manager.",
    htmlUrl: "https://github.com/oven-sh/bun",
    stargazersCount: 74900,
    forksCount: 2490,
    openIssuesCount: 1980,
    subscribersCount: 890,
    language: "Zig",
    topics: ["javascript", "typescript", "zig", "bundler", "runtime", "package-manager"],
    updatedAt: "2025-02-25T12:00:00Z",
    createdAt: "2021-04-12T19:30:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "main",
    weeklyGrowthStars: 2150,
  },
  {
    id: "54236920",
    name: "godot",
    fullName: "godotengine/godot",
    owner: {
      login: "godotengine",
      avatarUrl: "https://avatars.githubusercontent.com/u/6278832?v=4",
      htmlUrl: "https://github.com/godotengine",
    },
    description: "Godot Engine – Multi-platform 2D and 3D game engine.",
    htmlUrl: "https://github.com/godotengine/godot",
    stargazersCount: 92300,
    forksCount: 20400,
    openIssuesCount: 7890,
    subscribersCount: 2300,
    language: "C++",
    topics: ["game-engine", "gamedev", "2d", "3d", "cpp", "godot", "open-source"],
    updatedAt: "2025-02-24T22:15:00Z",
    createdAt: "2014-01-19T04:03:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "master",
    weeklyGrowthStars: 1900,
  },
  {
    id: "68930214",
    name: "tauri",
    fullName: "tauri-apps/tauri",
    owner: {
      login: "tauri-apps",
      avatarUrl: "https://avatars.githubusercontent.com/u/52643920?v=4",
      htmlUrl: "https://github.com/tauri-apps",
    },
    description: "Build smaller, faster, and more secure desktop and mobile applications with a web frontend.",
    htmlUrl: "https://github.com/tauri-apps/tauri",
    stargazersCount: 88400,
    forksCount: 2540,
    openIssuesCount: 430,
    subscribersCount: 980,
    language: "Rust",
    topics: ["rust", "desktop-app", "cross-platform", "gui", "tauri", "web-frontend"],
    updatedAt: "2025-02-25T09:30:00Z",
    createdAt: "2019-07-09T17:12:00Z",
    license: { key: "apache-2.0", name: "Apache License 2.0", spdxId: "Apache-2.0" },
    defaultBranch: "dev",
    weeklyGrowthStars: 1650,
  },
  {
    id: "598124901",
    name: "ui",
    fullName: "shadcn-ui/ui",
    owner: {
      login: "shadcn-ui",
      avatarUrl: "https://avatars.githubusercontent.com/u/124599895?v=4",
      htmlUrl: "https://github.com/shadcn-ui",
    },
    description: "Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.",
    htmlUrl: "https://github.com/shadcn-ui/ui",
    stargazersCount: 75200,
    forksCount: 5410,
    openIssuesCount: 190,
    subscribersCount: 620,
    language: "TypeScript",
    topics: ["tailwindcss", "react", "components", "ui", "radix-ui", "design-system"],
    updatedAt: "2025-02-25T15:20:00Z",
    createdAt: "2023-02-07T00:10:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "main",
    weeklyGrowthStars: 2890,
  },
  {
    id: "78912490",
    name: "uv",
    fullName: "astral-sh/uv",
    owner: {
      login: "astral-sh",
      avatarUrl: "https://avatars.githubusercontent.com/u/115961694?v=4",
      htmlUrl: "https://github.com/astral-sh",
    },
    description: "An extremely fast Python package and project manager, written in Rust.",
    htmlUrl: "https://github.com/astral-sh/uv",
    stargazersCount: 38600,
    forksCount: 890,
    openIssuesCount: 210,
    subscribersCount: 380,
    language: "Rust",
    topics: ["python", "rust", "package-manager", "pip", "virtualenv", "fast"],
    updatedAt: "2025-02-25T10:00:00Z",
    createdAt: "2023-10-18T14:22:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "main",
    weeklyGrowthStars: 3100,
  },
  {
    id: "12543900",
    name: "neovim",
    fullName: "neovim/neovim",
    owner: {
      login: "neovim",
      avatarUrl: "https://avatars.githubusercontent.com/u/6471485?v=4",
      htmlUrl: "https://github.com/neovim",
    },
    description: "Vim-fork focused on extensibility and usability.",
    htmlUrl: "https://github.com/neovim/neovim",
    stargazersCount: 83900,
    forksCount: 5800,
    openIssuesCount: 1650,
    subscribersCount: 1420,
    language: "Vim Script",
    topics: ["editor", "vim", "lua", "neovim", "text-editor", "cli"],
    updatedAt: "2025-02-25T13:00:00Z",
    createdAt: "2014-02-21T18:43:00Z",
    license: { key: "apache-2.0", name: "Apache License 2.0", spdxId: "Apache-2.0" },
    defaultBranch: "master",
    weeklyGrowthStars: 1240,
  },
  {
    id: "643128912",
    name: "vllm",
    fullName: "vllm-project/vllm",
    owner: {
      login: "vllm-project",
      avatarUrl: "https://avatars.githubusercontent.com/u/132890563?v=4",
      htmlUrl: "https://github.com/vllm-project",
    },
    description: "A high-throughput and memory-efficient inference and serving engine for LLMs.",
    htmlUrl: "https://github.com/vllm-project/vllm",
    stargazersCount: 36400,
    forksCount: 5200,
    openIssuesCount: 940,
    subscribersCount: 490,
    language: "Python",
    topics: ["ai", "llm-inference", "pagedattention", "cuda", "vllm", "python"],
    updatedAt: "2025-02-25T07:45:00Z",
    createdAt: "2023-04-19T21:10:00Z",
    license: { key: "apache-2.0", name: "Apache License 2.0", spdxId: "Apache-2.0" },
    defaultBranch: "main",
    weeklyGrowthStars: 2750,
  },
  {
    id: "89123490",
    name: "flutter",
    fullName: "flutter/flutter",
    owner: {
      login: "flutter",
      avatarUrl: "https://avatars.githubusercontent.com/u/14101776?v=4",
      htmlUrl: "https://github.com/flutter",
    },
    description: "Flutter makes it easy and fast to build beautiful apps for mobile and beyond.",
    htmlUrl: "https://github.com/flutter/flutter",
    stargazersCount: 167200,
    forksCount: 26800,
    openIssuesCount: 5400,
    subscribersCount: 3400,
    language: "Dart",
    topics: ["flutter", "mobile", "cross-platform", "dart", "android", "ios"],
    updatedAt: "2025-02-25T02:15:00Z",
    createdAt: "2015-03-06T22:54:00Z",
    license: { key: "bsd-3-clause", name: "BSD 3-Clause License", spdxId: "BSD-3-Clause" },
    defaultBranch: "master",
    weeklyGrowthStars: 1120,
  },
  {
    id: "34912084",
    name: "rust",
    fullName: "rust-lang/rust",
    owner: {
      login: "rust-lang",
      avatarUrl: "https://avatars.githubusercontent.com/u/5430905?v=4",
      htmlUrl: "https://github.com/rust-lang",
    },
    description: "Empowering everyone to build reliable and efficient software.",
    htmlUrl: "https://github.com/rust-lang/rust",
    stargazersCount: 98900,
    forksCount: 12900,
    openIssuesCount: 9800,
    subscribersCount: 2310,
    language: "Rust",
    topics: ["rust", "compiler", "programming-language", "systems-programming"],
    updatedAt: "2025-02-25T16:00:00Z",
    createdAt: "2010-06-16T20:41:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "master",
    weeklyGrowthStars: 1540,
  },
  {
    id: "90412895",
    name: "vscode",
    fullName: "microsoft/vscode",
    owner: {
      login: "microsoft",
      avatarUrl: "https://avatars.githubusercontent.com/u/6154722?v=4",
      htmlUrl: "https://github.com/microsoft",
    },
    description: "Visual Studio Code - Code editing. Redefined.",
    htmlUrl: "https://github.com/microsoft/vscode",
    stargazersCount: 161800,
    forksCount: 32400,
    openIssuesCount: 4200,
    subscribersCount: 3100,
    language: "TypeScript",
    topics: ["editor", "electron", "typescript", "vscode", "developer-tools"],
    updatedAt: "2025-02-25T11:20:00Z",
    createdAt: "2015-09-03T20:23:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "main",
    weeklyGrowthStars: 1320,
  },
  {
    id: "5892140",
    name: "pixijs",
    fullName: "pixijs/pixijs",
    owner: {
      login: "pixijs",
      avatarUrl: "https://avatars.githubusercontent.com/u/2629235?v=4",
      htmlUrl: "https://github.com/pixijs",
    },
    description: "The HTML5 Creation Engine: Create beautiful digital content with the fastest, most flexible 2D WebGL renderer.",
    htmlUrl: "https://github.com/pixijs/pixijs",
    stargazersCount: 43200,
    forksCount: 4900,
    openIssuesCount: 180,
    subscribersCount: 1100,
    language: "TypeScript",
    topics: ["2d", "webgl", "canvas", "gamedev", "pixijs", "javascript"],
    updatedAt: "2025-02-23T19:00:00Z",
    createdAt: "2013-02-13T01:31:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "main",
    weeklyGrowthStars: 640,
  },
  {
    id: "678912041",
    name: "ComfyUI",
    fullName: "comfyanonymous/ComfyUI",
    owner: {
      login: "comfyanonymous",
      avatarUrl: "https://avatars.githubusercontent.com/u/119187121?v=4",
      htmlUrl: "https://github.com/comfyanonymous",
    },
    description: "The most powerful and modular stable diffusion GUI and backend.",
    htmlUrl: "https://github.com/comfyanonymous/ComfyUI",
    stargazersCount: 56400,
    forksCount: 5900,
    openIssuesCount: 450,
    subscribersCount: 650,
    language: "Python",
    topics: ["ai", "stable-diffusion", "comfyui", "deep-learning", "image-generation"],
    updatedAt: "2025-02-25T05:30:00Z",
    createdAt: "2023-01-16T19:42:00Z",
    license: { key: "gpl-3.0", name: "GNU General Public License v3.0", spdxId: "GPL-3.0" },
    defaultBranch: "master",
    weeklyGrowthStars: 3400,
  },
  {
    id: "9481204",
    name: "zig",
    fullName: "ziglang/zig",
    owner: {
      login: "ziglang",
      avatarUrl: "https://avatars.githubusercontent.com/u/31752187?v=4",
      htmlUrl: "https://github.com/ziglang",
    },
    description: "General-purpose programming language and toolchain for maintaining robust, optimal and reusable software.",
    htmlUrl: "https://github.com/ziglang/zig",
    stargazersCount: 35100,
    forksCount: 2310,
    openIssuesCount: 2450,
    subscribersCount: 780,
    language: "Zig",
    topics: ["zig", "compiler", "programming-language", "systems-programming", "c-replacement"],
    updatedAt: "2025-02-25T14:10:00Z",
    createdAt: "2015-09-24T05:28:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "master",
    weeklyGrowthStars: 1890,
  },
  {
    id: "882194510",
    name: "git-crazy",
    fullName: "gitcrazy/git-crazy",
    owner: {
      login: "gitcrazy",
      avatarUrl: "https://avatars.githubusercontent.com/u/10000000?v=4",
      htmlUrl: "https://github.com/gitcrazy",
    },
    description: "Worldwide discovery, collection, bookmarking, and tracking platform for interesting and famous GitHub repositories.",
    htmlUrl: "https://github.com/gitcrazy/git-crazy",
    stargazersCount: 14200,
    forksCount: 1890,
    openIssuesCount: 12,
    subscribersCount: 340,
    language: "TypeScript",
    topics: ["github", "retro-ui", "pixel-art", "msix", "discovery", "desktop-app", "nextjs"],
    updatedAt: "2025-02-25T18:00:00Z",
    createdAt: "2025-02-01T12:00:00Z",
    license: { key: "mit", name: "MIT License", spdxId: "MIT" },
    defaultBranch: "main",
    weeklyGrowthStars: 4900,
  }
];

export const VERIFIED_QUOTES = [
  {
    quote: "Talk is cheap. Show me the code.",
    author: "Linus Torvalds",
    role: "Creator of Linux & Git",
  },
  {
    quote: "Simplicity is prerequisite for reliability.",
    author: "Edsger W. Dijkstra",
    role: "Pioneer in Computer Science",
  },
  {
    quote: "The open source community is powered by curiosity, collaboration, and passion.",
    author: "Sarah Drasner",
    role: "VP of Engineering & Open Source Advocate",
  },
  {
    quote: "Code is like humor. When you have to explain it, it’s bad.",
    author: "Cory House",
    role: "Software Architect",
  },
  {
    quote: "Building software is a collective superpower shared across global boundaries.",
    author: "Mitchell Hashimoto",
    role: "Creator of Vagrant, Terraform & Vault",
  },
  {
    quote: "Readability counts. Beautiful is better than ugly.",
    author: "Guido van Rossum",
    role: "Creator of Python",
  },
  {
    quote: "GitHub is the town square of the world's developers.",
    author: "Nat Friedman",
    role: "Former CEO of GitHub",
  }
];
